# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2cfb539a-e2b6-4e86-877c-6aa6b7b3f822"
    keyvaultName: "privateakskeyvault"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: ExampleSecret
          objectType: secret
          objectVersion: ""
        - |
          objectName: 2ndExampleSecret
          objectType: secret
          objectVersion: ""
        - |
          objectName: key1
          objectType: key
          objectVersion: ""
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47" 
